Resolve some compiler errors in ast_sockaddr_is_any().
These errors came up once this function was used from within netsock2.c.
The errors were like the following:

netsock2.c:393: error: dereferencing pointer ‘({anonymous})’ does break strict-aliasing rules

The usage of a union here avoids this problem.


git-svn-id: http://svn.asterisk.org/svn/asterisk/branches/1.8@292188 f38db490-d61c-443f-a65b-d21fe96a405b